// AUTO-GENERATED by scripts/generate-price-plan-map.js — do not edit by hand.
// Source of truth: src/constants/plans.js (the `stripe` field on each plan).
// Regenerate after changing that file: node scripts/generate-price-plan-map.js
//
// Used by create-checkout.js to derive the real plan from the Stripe price
// actually being charged, instead of trusting a client-supplied planId that
// could be set to a higher-value plan than the price paid for.
"use strict";

module.exports = {
  "price_1TpbitIxMNaZk137A5viyNCb": "individual",
  "price_1TpbkAIxMNaZk137jWqHeHDb": "individual",
  "price_1TpbkrIxMNaZk137XB9lFqFF": "family",
  "price_1TpblxIxMNaZk137BKjgCOl4": "family",
  "price_1TsbD5IxMNaZk137PacaFJRf": "university-bundle",
  "price_1TsbD6IxMNaZk137LiewJ3F1": "university-bundle",
  "price_1TrR5oIxMNaZk137JqipjbLU": "career-ready",
  "price_1TrRO5IxMNaZk137IsgSb6Zj": "career-ready",
  "price_1TrR8zIxMNaZk137LTnyIHAL": "global-ready",
  "price_1TrRP3IxMNaZk137TJRI92xk": "global-ready",
  "price_1TsJDfIxMNaZk137Dj2OH5z4": "speak-ready",
  "price_1TsJFJIxMNaZk137JgAaIjjF": "speak-ready",
  "price_1Tn5MWIxMNaZk137s02Hgc5l": "all_access",
  "price_1Tn5MYIxMNaZk137eAmWFQE0": "all_access",
  "price_1Tn5MNIxMNaZk1378uLJ3mvO": "phonics",
  "price_1Tn5MQIxMNaZk137IcXcUb86": "phonics",
  "price_1TicIRIxMNaZk1371JdtuVkF": "eiken",
  "price_1TicISIxMNaZk137jXrCViFM": "eiken",
  "price_1Tn5MnIxMNaZk137gfxeyRSE": "wondercamp",
  "price_1Tn5MpIxMNaZk137PCanjKPv": "wondercamp",
  "price_1TicISIxMNaZk13795L4kNwO": "sipswitch",
  "price_1TicITIxMNaZk137oTlKK6ZS": "sipswitch",
  "price_1TicIUIxMNaZk137GBUtmSzX": "speak",
  "price_1TicIUIxMNaZk137wmSaPtb7": "speak",
  "price_1TicIVIxMNaZk1379TRmqgzQ": "innerkey",
  "price_1TicIVIxMNaZk137lpS521aS": "innerkey",
  "price_1Tn5MSIxMNaZk137pVDCDNbm": "kids_starter",
  "price_1Tn5MUIxMNaZk137g0Y3hREC": "kids_starter",
  "price_1TicIYIxMNaZk137muKBEOGa": "english_boost",
  "price_1TicIYIxMNaZk137Us9D8G8B": "english_boost",
  "price_1TicIZIxMNaZk1374JSur2re": "adult_growth",
  "price_1TicIaIxMNaZk1377YwVDu2t": "adult_growth",
  "price_1TicIcIxMNaZk137U6xjyQvi": "adult_complete",
  "price_1TicIcIxMNaZk137sHthQBMC": "adult_complete",
  "price_1TnagjIxMNaZk137pzA7MVmv": "family_core",
  "price_1Tnai6IxMNaZk137zYHSznc2": "family_core",
  "price_1Tnai8IxMNaZk137DowXFIHs": "family_plus",
  "price_1TnaiTIxMNaZk137PT4WXsVh": "family_plus",
  "price_1TnaiBIxMNaZk1378n8Urtek": "family_premium",
  "price_1TnaifIxMNaZk1377I2i888y": "family_premium",
};
