export const ACCESS_CODES = {
  "KINDER-HSD-2026": {
    codeType: "Kindergarten Access Code",
    source: "kindergarten",
    campaignCategory: "Kindergarten",
    campaignName: "Kindergarten Family Access Campaign",
    accessDays: 30,
    aiCredits: 30,
    fullPlatformAccess: true,
    active: true,
    userFacingDesc: "Enter your kindergarten access code to unlock 1 month of full HSDOS.AI platform access and 30 AI practice credits for kids, families, phonics, EIKEN practice, speaking confidence, and parent-child English.",
  },
  "UNI-READY-HSD": {
    codeType: "University Access Code",
    source: "university",
    campaignCategory: "University",
    campaignName: "University Full Platform Access Campaign",
    accessDays: 30,
    aiCredits: 30,
    fullPlatformAccess: true,
    active: true,
    userFacingDesc: "Enter your university access code to unlock 1 month of full HSDOS.AI platform access and 30 AI practice credits. Includes Career Ready, Global Ready, Speak Ready, and all other learning paths.",
  },
  "FAMILY-HSD-2026": {
    codeType: "Family Access Code",
    source: "family",
    campaignCategory: "Family",
    campaignName: "Family Free Month Campaign",
    accessDays: 30,
    aiCredits: 30,
    fullPlatformAccess: true,
    active: true,
    userFacingDesc: "Enter your family access code to unlock 1 month of full HSDOS.AI platform access and 30 AI practice credits for parent-child English, travel English, speaking practice, and family confidence building.",
  },
  "TEACHER-HSD-2026": {
    codeType: "Teacher Access Code",
    source: "teacher",
    campaignCategory: "Teacher",
    campaignName: "Teacher Access Campaign",
    accessDays: 30,
    aiCredits: 30,
    fullPlatformAccess: true,
    active: true,
    userFacingDesc: "Enter your teacher access code to unlock 1 month of full HSDOS.AI platform access and 30 AI practice credits for classroom support, pronunciation, lesson ideas, and communication training.",
  },
  "WORKSHOP-HSD-2026": {
    codeType: "Workshop Access Code",
    source: "workshop_event_partner",
    campaignCategory: "Workshop / Event / Partner",
    campaignName: "Workshop Event Partner Access Campaign",
    accessDays: 30,
    aiCredits: 30,
    fullPlatformAccess: true,
    active: true,
    userFacingDesc: "Enter your workshop access code to unlock 1 month of full HSDOS.AI platform access and 30 AI practice credits for speaking practice, presentation practice, confidence challenges, and real-world English communication.",
  },
  "GYM-HSD-2026": {
    codeType: "Gym Access Code",
    source: "gym",
    campaignCategory: "Gym / Fitness",
    campaignName: "Gym Partner Access Campaign",
    accessDays: 30,
    aiCredits: 30,
    fullPlatformAccess: true,
    active: true,
    userFacingDesc: "Train your body. Build your English confidence. Enter your gym access code to unlock 1 month of full HSDOS.AI platform access and 30 AI practice credits.",
  },
  "XPRIZE-JUDGE-2026": {
    codeType: "Judge Access Code",
    source: "xprize_judge",
    campaignCategory: "Workshop / Event / Partner",
    campaignName: "Build with Gemini XPRIZE — Judge Access",
    accessDays: 90,
    aiCredits: 100,
    fullPlatformAccess: true,
    active: true,
    userFacingDesc: "Judge access code for the Build with Gemini XPRIZE — unlocks 90 days of full HSDOS.AI platform access and 100 AI practice credits across every World, including Jona Coach, EIKEN AI, and the university and adult tracks.",
  },
};

export const INACTIVE_CODES = [
  "CAREER-READY-30",
  "GLOBAL-READY-30",
  "SPEAK-READY-30",
  "CHIGUSA-HSD-2026",
  "PARTNER-HSD-2026",
  "EVENT-HSD-2026",
];
