// HSD OS – App Registry
// Single source of truth for all registered applications.
// Future apps (including third-party) register here to connect to the OS.

export const APP_REGISTRY = [
  {
    appId:                   "phonics",
    appName:                 "Monkey Yoga Phonics™",
    category:                "kids",
    audience:                ["children", "parents"],
    description:             "Phonics mastery through movement and music for young learners",
    status:                  "active",
    analyticsEnabled:        true,
    confidenceTracked:       true,
    skillsTargeted:          ["pronunciation", "listening", "reading"],
    subscriptionRequirements: ["individual", "family", "phonics", "kids_starter", "all_access"],
    version:                 "1.0",
    vendor:                  "Hear See Do Empire",
  },
  {
    appId:                   "eiken",
    appName:                 "EIKEN AI Monkey",
    category:                "kids",
    audience:                ["students", "test_prep"],
    description:             "AI-powered EIKEN exam preparation with adaptive practice",
    status:                  "active",
    analyticsEnabled:        true,
    confidenceTracked:       true,
    skillsTargeted:          ["vocabulary", "grammar", "reading", "listening"],
    subscriptionRequirements: ["individual", "family", "eiken", "english_boost", "adult_complete", "all_access"],
    version:                 "1.0",
    vendor:                  "Hear See Do Empire",
  },
  {
    appId:                   "speak",
    appName:                 "Speak & Sweat",
    category:                "kids",
    audience:                ["all_ages"],
    description:             "Build speaking confidence through active learning and movement",
    status:                  "active",
    analyticsEnabled:        true,
    confidenceTracked:       true,
    skillsTargeted:          ["speaking", "pronunciation", "confidence"],
    subscriptionRequirements: ["individual", "family", "speak", "adult_growth", "all_access"],
    version:                 "1.0",
    vendor:                  "Hear See Do Empire",
  },
  {
    appId:                   "wondercamp",
    appName:                 "Wondercamp",
    category:                "kids",
    audience:                ["children"],
    description:             "Immersive English adventure camp experience for kids",
    status:                  "active",
    analyticsEnabled:        true,
    confidenceTracked:       true,
    skillsTargeted:          ["listening", "speaking", "vocabulary"],
    subscriptionRequirements: ["individual", "family", "wondercamp", "kids_starter", "all_access"],
    version:                 "1.0",
    vendor:                  "Hear See Do Empire",
  },
  {
    appId:                   "family",
    appName:                 "HSD Family",
    category:                "family",
    audience:                ["families"],
    description:             "Shared family English learning with progress tracking for all members",
    status:                  "active",
    analyticsEnabled:        true,
    confidenceTracked:       true,
    skillsTargeted:          ["speaking", "listening", "vocabulary"],
    subscriptionRequirements: ["individual", "family", "all_access"],
    version:                 "1.0",
    vendor:                  "Hear See Do Empire",
  },
  {
    appId:                   "sipswitch",
    appName:                 "Sip & Switch™",
    category:                "adult",
    audience:                ["adults", "professionals"],
    description:             "English fluency through conversational switching — perfect for daily life",
    status:                  "active",
    analyticsEnabled:        true,
    confidenceTracked:       true,
    skillsTargeted:          ["listening", "speaking", "vocabulary"],
    subscriptionRequirements: ["individual", "family", "sipswitch", "english_boost", "adult_growth", "adult_complete", "all_access"],
    version:                 "1.0",
    vendor:                  "Hear See Do Empire",
  },
  {
    appId:                   "innerkey",
    appName:                 "The Inner Key Blueprint™",
    category:                "adult",
    audience:                ["adults"],
    description:             "Mindset and confidence development for transformational English growth",
    status:                  "active",
    analyticsEnabled:        true,
    confidenceTracked:       true,
    skillsTargeted:          ["mindset", "speaking", "confidence"],
    subscriptionRequirements: ["individual", "family", "innerkey", "adult_complete", "all_access"],
    version:                 "1.0",
    vendor:                  "Hear See Do Empire",
  },
];

export const APP_REGISTRY_MAP = Object.fromEntries(APP_REGISTRY.map(a => [a.appId, a]));

// Apps can subscribe to OS events. Future hook system:
// OS_EVENTS = ["confidence_updated", "skill_updated", "recommendation_generated", "milestone_reached"]
