// All 7 HSD OS apps
// iframeUrl is read from env at runtime; falls back to branded placeholder
export const APPS = [
  {
    id: "phonics",
    name: "Monkey Yoga Phonics™",
    desc: "Phonics • Yoga • Mind • Body",
    icon: "🎵",
    image: "/assets/icon-phonics.png",
    cardImage: "/assets/worlds/monkey-yoga-card.jpg",
    accent: "#e01010",
    audience: "kids",
    price: 980,
    iframeUrl: import.meta.env.VITE_APP_URL_PHONICS || "",
  },
  {
    id: "eiken",
    name: "Eiken AI Monkey",
    desc: "Study Japanese with AI",
    icon: "🐒",
    image: "/assets/icon-eiken.png",
    cardImage: "/assets/worlds/eiken-card.jpg",
    accent: "#e01010",
    audience: "kids",
    price: 1280,
    iframeUrl: "", // native page — see AppModal's eiken special-case (not an iframe sub-app)
  },
  {
    id: "speak",
    name: "Speak & Sweat",
    desc: "Speak English. Build Confidence.",
    icon: "💬",
    image: "/assets/icon-speak.png",
    cardImage: "/assets/worlds/speak-sweat-card.jpg",
    accent: "#e01010",
    audience: "adult",
    price: 980,
    iframeUrl: import.meta.env.VITE_APP_URL_SPEAK || "",
  },
  {
    id: "wondercamp",
    name: "Wondercamp",
    desc: "Adventures in Learning",
    icon: "🏕️",
    image: "/assets/icon-wondercamp.png",
    cardImage: "/assets/worlds/wondercamp-card.jpg",
    accent: "#e01010",
    audience: "kids",
    price: 1680,
    iframeUrl: import.meta.env.VITE_APP_URL_WONDERCAMP || "",
  },
  {
    id: "family",
    name: "HSD Family",
    desc: "Track your family's learning journey",
    icon: "👨‍👩‍👧",
    image: "/assets/icon-family.png",
    cardImage: "/assets/worlds/family-card.jpg",
    accent: "#22c55e",
    audience: "both",
    price: 680,
    free: true,
    badge: "FREE",
    iframeUrl: import.meta.env.VITE_APP_URL_FAMILY || "",
  },
  {
    id: "music-album",
    name: "The HSD Album",
    desc: "Seasonal & holiday sing-along CDs by Jonathan Waltho",
    icon: "💿",
    image: "/assets/icon-family.png",
    cardImage: "/assets/worlds/family-card.jpg",
    accent: "#C9A84C",
    audience: "both",
    price: 0,
    free: true,
    badge: "FREE",
    launchMode: "external",
    iframeUrl: import.meta.env.VITE_APP_URL_ALBUM || "https://hearseedo-album.netlify.app",
  },
  {
    id: "sipswitch",
    name: "Sip & Switch™",
    desc: "English Conversation. One Sip at a Time.",
    icon: "☕",
    image: "/assets/icon-sipswitch.png",
    cardImage: "/assets/worlds/sip-switch-card.jpg",
    accent: "#7B5EA7",
    audience: "adult",
    price: 1280,
    iframeUrl: import.meta.env.VITE_APP_URL_SIPSWITCH || "",
  },
  {
    id: "innerkey",
    name: "The Inner Key Blueprint™",
    desc: "Unlock the Mind. Transform the Life.",
    icon: "🔑",
    image: "/assets/innerkey/icon-128.png",
    cardImage: "/assets/worlds/innerkey-card.jpg",
    accent: "#C9A84C",
    audience: "adult",
    price: 1480,
    iframeUrl: import.meta.env.VITE_APP_URL_INNERKEY || "",
  },
  {
    id: "monkeys-unlock",
    name: "Monkeys Unlock™: Monkey Escape",
    desc: "Hear it. See it. Say it. Unlock the room.",
    icon: "🗝️",
    image: null,
    cardImage: "/assets/worlds/monkeys-unlock-card.jpg",
    accent: "#2f6fed",
    audience: "family",
    price: 980,
    comingSoon: true,
    iframeUrl: import.meta.env.VITE_APP_URL_MONKEYS_UNLOCK || "",
  },
  {
    id: "career-ready",
    name: "Career Ready",
    desc: "English confidence for university life and career",
    icon: "🎓",
    image: "/assets/icon-career-ready.png",
    cardImage: "/assets/worlds/career-ready-card.jpg",
    accent: "#2ec4b6",
    audience: "university",
    price: 1980,
    badge: "NEW",
    iframeUrl: "", // native page at /career-ready — see AppModal special-case
  },
  {
    id: "global-ready",
    name: "Global Ready",
    desc: "English confidence for study abroad, travel, and international life",
    icon: "🌍",
    image: "/assets/icon-global-ready.png",
    cardImage: "/assets/worlds/global-ready-card.jpg",
    accent: "#e01010",
    audience: "university",
    price: 1980,
    badge: "NEW",
    iframeUrl: "", // native page at /global-ready — see AppModal special-case
  },
  {
    id: "speak-ready",
    name: "Speak Ready",
    desc: "Confidence-first speaking practice for real life",
    icon: "🗣️",
    image: "/assets/icon-speak-ready.png",
    accent: "#f59e0b",
    audience: "university",
    price: 1980,
    badge: "NEW",
    iframeUrl: "", // native page at /speak-ready — see AppModal special-case
  },
];

// Orbit layouts per view
export const ORBIT_LAYOUTS = {
  kids: [
    { id: "eiken",          position: "top-left"  },
    { id: "speak",          position: "top-right" },
    { id: "phonics",        position: "mid-left"  },
    { id: "wondercamp",     position: "mid-right" },
    { id: "monkeys-unlock", position: "bottom-left" },
    { id: "family",         position: "bottom"    },
  ],
  adult: [
    { id: "sipswitch", position: "mid-left"  },
    { id: "innerkey",  position: "mid-right" },
    { id: "family",    position: "bottom"    },
  ],
  all: [
    { id: "eiken",          position: "top-left"    },
    { id: "speak",          position: "top-right"   },
    { id: "phonics",        position: "mid-left"    },
    { id: "wondercamp",     position: "mid-right"   },
    { id: "monkeys-unlock", position: "bottom-left" },
    { id: "sipswitch",      position: "bottom-left" },
    { id: "innerkey",       position: "bottom-right"},
    { id: "family",         position: "bottom"      },
  ],
};

export const APP_MAP = Object.fromEntries(APPS.map((a) => [a.id, a]));
