export const PLANS = [
  {
    id: "phonics",
    name: "Monkey Yoga Phonics",
    nameJp: "モンキーヨガフォニックス",
    desc: "Phonics and movement for young learners. Books 1–4 with Book 1 free forever.",
    price_monthly: 833,
    price_yearly: 8330,
    reg_price: 980,
    apps: ["phonics"],
    ai_msgs: 15,
    stripe: {
      monthly: "price_1TicIQIxMNaZk137aOQ0RqGQ",
      yearly:  "price_1TicIRIxMNaZk137YvD6AOKz",
    },
    color: "#4488ff",
    badge: null,
  },
  {
    id: "eiken",
    name: "Eiken Monkey",
    nameJp: "英検モンキー",
    desc: "Complete EIKEN prep Grade 5 to Pre-1 with AI speaking built in.",
    price_monthly: 1258,
    price_yearly: 12580,
    reg_price: 1480,
    apps: ["eiken"],
    ai_msgs: 15,
    stripe: {
      monthly: "price_1TicIRIxMNaZk1371JdtuVkF",
      yearly:  "price_1TicISIxMNaZk137jXrCViFM",
    },
    color: "#e01010",
    badge: "Most Popular",
  },
  {
    id: "sipswitch",
    name: "Sip & Switch",
    nameJp: "シップ＆スイッチ",
    desc: "Adult AI conversation practice. Flexible, adaptive, 15 minutes a session.",
    price_monthly: 1088,
    price_yearly: 10880,
    reg_price: 1280,
    apps: ["sipswitch"],
    ai_msgs: 15,
    stripe: {
      monthly: "price_1TicISIxMNaZk13795L4kNwO",
      yearly:  "price_1TicITIxMNaZk137oTlKK6ZS",
    },
    color: "#7B5EA7",
    badge: null,
  },
  {
    id: "speak",
    name: "Speak & Sweat",
    nameJp: "スピーク＆スウェット",
    desc: "Confidence through movement and communication.",
    price_monthly: 1020,
    price_yearly: 10200,
    reg_price: 1200,
    apps: ["speak"],
    ai_msgs: 15,
    stripe: {
      monthly: "price_1TicIUIxMNaZk137GBUtmSzX",
      yearly:  "price_1TicIUIxMNaZk137wmSaPtb7",
    },
    color: "#22c55e",
    badge: null,
  },
  {
    id: "innerkey",
    name: "InnerKey",
    nameJp: "インナーキー",
    desc: "Unlock. Rewire. Radiate. Personal growth through the Inner Key Series™.",
    price_monthly: 1258,
    price_yearly: 12580,
    reg_price: 1480,
    apps: ["innerkey"],
    ai_msgs: 15,
    stripe: {
      monthly: "price_1TicIVIxMNaZk1379TRmqgzQ",
      yearly:  "price_1TicIVIxMNaZk137lpS521aS",
    },
    color: "#f59e0b",
    badge: null,
  },
  {
    id: "kids_starter",
    name: "Young Learner Bundle",
    nameJp: "ヤングラーナーバンドル",
    desc: "Wondercamp + Monkey Yoga Phonics. The complete early English journey.",
    price_monthly: 2480,
    price_yearly: 24800,
    reg_price: 2900,
    apps: ["phonics", "wondercamp"],
    ai_msgs: 30,
    stripe: {
      monthly: "price_1TicIWIxMNaZk137JEOT7cXu",
      yearly:  "price_1TicIXIxMNaZk1377hgS7Ka2",
    },
    color: "#4488ff",
    badge: "Bundle",
  },
  {
    id: "english_boost",
    name: "Exam + Convo Bundle",
    nameJp: "試験＋会話バンドル",
    desc: "Eiken Monkey + Sip & Switch. Study and speak.",
    price_monthly: 2108,
    price_yearly: 21080,
    reg_price: 2480,
    apps: ["eiken", "sipswitch"],
    ai_msgs: 30,
    stripe: {
      monthly: "price_1TicIYIxMNaZk137muKBEOGa",
      yearly:  "price_1TicIYIxMNaZk137Us9D8G8B",
    },
    color: "#e01010",
    badge: "Bundle",
  },
  {
    id: "adult_growth",
    name: "Active Adult Bundle",
    nameJp: "アクティブ大人バンドル",
    desc: "Speak & Sweat + Sip & Switch. Move, speak, grow.",
    price_monthly: 1853,
    price_yearly: 18530,
    reg_price: 2180,
    apps: ["speak", "sipswitch"],
    ai_msgs: 30,
    stripe: {
      monthly: "price_1TicIZIxMNaZk1374JSur2re",
      yearly:  "price_1TicIaIxMNaZk1377YwVDu2t",
    },
    color: "#22c55e",
    badge: "Bundle",
  },
  {
    id: "family_full",
    name: "Family Complete Bundle",
    nameJp: "ファミリー完全バンドル",
    desc: "HSD Family + Phonics + Wondercamp. English for the whole family.",
    price_monthly: 2858,
    price_yearly: 28580,
    reg_price: 3360,
    apps: ["family", "phonics", "wondercamp"],
    ai_msgs: 30,
    stripe: {
      monthly: "price_1TicIaIxMNaZk137IdoAG5xv",
      yearly:  "price_1TicIbIxMNaZk137oFxCXLsy",
    },
    color: "#f59e0b",
    badge: "Bundle",
  },
  {
    id: "adult_complete",
    name: "Adult Complete Bundle",
    nameJp: "大人完全バンドル",
    desc: "Eiken + Sip & Switch + InnerKey. The complete adult English system.",
    price_monthly: 2873,
    price_yearly: 28730,
    reg_price: 3380,
    apps: ["eiken", "sipswitch", "innerkey"],
    ai_msgs: 30,
    stripe: {
      monthly: "price_1TicIcIxMNaZk137U6xjyQvi",
      yearly:  "price_1TicIcIxMNaZk137sHthQBMC",
    },
    color: "#7B5EA7",
    badge: "Bundle",
  },
  {
    id: "all_access",
    name: "All Access",
    nameJp: "オールアクセス",
    desc: "Every HSD app. Unlimited AI. The complete English ecosystem.",
    price_monthly: 4680,
    price_yearly: 46800,
    reg_price: 5500,
    apps: ["phonics", "eiken", "speak", "sipswitch", "wondercamp", "family", "innerkey"],
    ai_msgs: 100,
    stripe: {
      monthly: "price_1TicIdIxMNaZk137G3NXTVfb",
      yearly:  "price_1TicIdIxMNaZk1374kCylvKO",
    },
    color: "#e01010",
    badge: "Best Value",
  },
];

export const AI_LIMITS = {
  free:           5,
  phonics:        15,
  eiken:          15,
  sipswitch:      15,
  speak:          15,
  innerkey:       15,
  kids_starter:   30,
  english_boost:  30,
  adult_growth:   30,
  family_full:    30,
  adult_complete: 30,
  all_access:     100,
};
