/* ─── Active plans shown to users ─────────────────────────────────────────── */
export const PLANS = [
  {
    id: "free",
    name: "Free",
    nameJp: "無料",
    desc: "Start your English journey. No credit card needed.",
    price_monthly: 0,
    price_yearly: 0,
    ai_msgs: 5,
    members: 1,
    color: "#4488ff",
    badge: "Free",
    legacy: false,
    stripe: { monthly: null, yearly: null },
    features: [
      "5 Jona AI messages/month",
      "Access to free lessons",
      "Progress dashboard",
    ],
  },
  {
    id: "individual",
    name: "Individual",
    nameJp: "個人プラン",
    desc: "Full access to every HSD app. EIKEN prep, phonics, conversation practice — all in one plan.",
    price_monthly: 2480,
    price_yearly: 19800,
    ai_msgs: 50,
    members: 1,
    color: "#4488ff",
    badge: null,
    legacy: false,
    stripe: { monthly: "price_1TpbitIxMNaZk137A5viyNCb", yearly: "price_1TpbkAIxMNaZk137jWqHeHDb" },
    features: [
      "All HSD apps unlocked",
      "50 Jona AI messages/month",
      "EIKEN prep Grade 5 to Pre-1",
      "Phonics, speaking & conversation tools",
      "Daily coaching card",
      "Progress dashboard",
    ],
  },
  {
    id: "family",
    name: "Family",
    nameJp: "ファミリープラン",
    desc: "Everything in Individual, shared with up to 5 family members. Kids and adults — one price.",
    price_monthly: 3980,
    price_yearly: 34800,
    ai_msgs: 100,
    members: 5,
    color: "#e01010",
    badge: "Best Value",
    legacy: false,
    stripe: { monthly: "price_1TpbkrIxMNaZk137XB9lFqFF", yearly: "price_1TpblxIxMNaZk137BKjgCOl4" },
    features: [
      "All HSD apps for every family member",
      "Up to 5 members (kids + adults)",
      "100 Jona AI messages/month",
      "Individual profiles per member",
      "Family progress dashboard",
      "All future apps included",
    ],
  },
  // ── Legacy plans kept for existing subscribers / admin display ─────────────
  { id: "all_access",     name: "All Access",           nameJp: "オールアクセス",          legacy: true, price_monthly: 4980, price_yearly: 49800,  ai_msgs: 100, color: "#e01010",  stripe: { monthly: "price_1Tn5MWIxMNaZk137s02Hgc5l", yearly: "price_1Tn5MYIxMNaZk137eAmWFQE0" }, features: [] },
  { id: "phonics",        name: "Monkey Yoga Phonics",  nameJp: "モンキーヨガフォニックス",  legacy: true, price_monthly: 1280, price_yearly: 12800,  ai_msgs:  15, color: "#4488ff",  stripe: { monthly: "price_1Tn5MNIxMNaZk1378uLJ3mvO", yearly: "price_1Tn5MQIxMNaZk137IcXcUb86" }, features: [] },
  { id: "eiken",          name: "Eiken Monkey",         nameJp: "英検モンキー",             legacy: true, price_monthly: 1258, price_yearly: 12580,  ai_msgs:  15, color: "#e01010",  stripe: { monthly: "price_1TicIRIxMNaZk1371JdtuVkF", yearly: "price_1TicISIxMNaZk137jXrCViFM" }, features: [] },
  { id: "wondercamp",     name: "Wondercamp",           nameJp: "ワンダーキャンプ",         legacy: true, price_monthly: 1680, price_yearly: 16800,  ai_msgs:  15, color: "#FF8A6B", stripe: { monthly: "price_1Tn5MnIxMNaZk137gfxeyRSE", yearly: "price_1Tn5MpIxMNaZk137PCanjKPv" }, features: [] },
  { id: "sipswitch",      name: "Sip & Switch",         nameJp: "シップ＆スイッチ",         legacy: true, price_monthly: 1088, price_yearly: 10880,  ai_msgs:  15, color: "#7B5EA7", stripe: { monthly: "price_1TicISIxMNaZk13795L4kNwO", yearly: "price_1TicITIxMNaZk137oTlKK6ZS" }, features: [] },
  { id: "speak",          name: "Speak & Sweat",        nameJp: "スピーク＆スウェット",     legacy: true, price_monthly: 1020, price_yearly: 10200,  ai_msgs:  15, color: "#22c55e", stripe: { monthly: "price_1TicIUIxMNaZk137GBUtmSzX", yearly: "price_1TicIUIxMNaZk137wmSaPtb7" }, features: [] },
  { id: "innerkey",       name: "InnerKey",             nameJp: "インナーキー",             legacy: true, price_monthly: 1258, price_yearly: 12580,  ai_msgs:  15, color: "#f59e0b", stripe: { monthly: "price_1TicIVIxMNaZk1379TRmqgzQ", yearly: "price_1TicIVIxMNaZk137lpS521aS" }, features: [] },
  { id: "kids_starter",   name: "Young Learner Bundle", nameJp: "ヤングラーナーバンドル",   legacy: true, price_monthly: 2780, price_yearly: 27800,  ai_msgs:  30, color: "#4488ff",  stripe: { monthly: "price_1Tn5MSIxMNaZk137pVDCDNbm", yearly: "price_1Tn5MUIxMNaZk137g0Y3hREC" }, features: [] },
  { id: "english_boost",  name: "Exam + Convo Bundle",  nameJp: "試験＋会話バンドル",       legacy: true, price_monthly: 2108, price_yearly: 21080,  ai_msgs:  30, color: "#e01010",  stripe: { monthly: "price_1TicIYIxMNaZk137muKBEOGa", yearly: "price_1TicIYIxMNaZk137Us9D8G8B" }, features: [] },
  { id: "adult_growth",   name: "Active Adult Bundle",  nameJp: "アクティブ大人バンドル",   legacy: true, price_monthly: 1853, price_yearly: 18530,  ai_msgs:  30, color: "#22c55e", stripe: { monthly: "price_1TicIZIxMNaZk1374JSur2re", yearly: "price_1TicIaIxMNaZk1377YwVDu2t" }, features: [] },
  { id: "adult_complete", name: "Adult Complete Bundle", nameJp: "大人完全バンドル",        legacy: true, price_monthly: 2873, price_yearly: 28730,  ai_msgs:  30, color: "#7B5EA7", stripe: { monthly: "price_1TicIcIxMNaZk137U6xjyQvi", yearly: "price_1TicIcIxMNaZk137sHthQBMC" }, features: [] },
  { id: "family_core",    name: "Family Core",          nameJp: "ファミリーコア",           legacy: true, price_monthly: 2780, price_yearly: 27800,  ai_msgs:  30, color: "#4488ff",  stripe: { monthly: "price_1TnagjIxMNaZk137pzA7MVmv", yearly: "price_1Tnai6IxMNaZk137zYHSznc2" }, features: [] },
  { id: "family_plus",    name: "Family Plus",          nameJp: "ファミリープラス",         legacy: true, price_monthly: 4280, price_yearly: 42800,  ai_msgs:  60, color: "#e01010",  stripe: { monthly: "price_1Tnai8IxMNaZk137DowXFIHs", yearly: "price_1TnaiTIxMNaZk137PT4WXsVh" }, features: [] },
  { id: "family_premium", name: "Family Premium",       nameJp: "ファミリープレミアム",     legacy: true, price_monthly: 5980, price_yearly: 59800,  ai_msgs: 100, color: "#C9A84C", stripe: { monthly: "price_1TnaiBIxMNaZk1378n8Urtek", yearly: "price_1TnaifIxMNaZk1377I2i888y" }, features: [] },
];

/* ─── Backwards-compat exports for Admin.jsx ─────────────────────────────── */
export const FAMILY_PLANS = PLANS.filter(p => p.id.startsWith("family_") && p.legacy);

/* ─── AI message limits by plan ─────────────────────────────────────────── */
export const AI_LIMITS = Object.fromEntries(PLANS.map(p => [p.id, p.ai_msgs ?? 5]));
