// Sip Speak Learn — structured course content
// SOURCE OF TRUTH: the four seasonal workbooks (Spring / Summer / Fall / Winter
// Editions). Content is transcribed here as structured data so it is never
// hardcoded inside page components. 4 seasons × 8 lessons = 32 conversations.
//
// Lesson shape:
//   { id, n, theme, setting, objective,
//     dialogue: [{ speaker, line }],
//     cocktail: { name, ingredients, note },
//     mocktail: { name, ingredients, note },
//     keyPhrases: [string ×6],
//     pairQuestions: [string ×2],
//     rolePlay: string,
//     mixAndSpeak: [string ×3],
//     levels: { beginner, intermediate, advanced },
//     reflection: string }

export const REFLECTION_ORDER = "What would you order, and who would you enjoy it with?";

export const SEASONS = [
  {
    id: "spring",
    name: "Spring Café",
    edition: "Spring Edition",
    tagline: "Fresh starts and sunny-morning conversation.",
    description: "Eight bright conversations for new beginnings and easy connection.",
    accent: "#d98a94",
    icon: "❀",
    image: "/ssl/ssl-season-spring.jpg",
    strip: "/ssl/ssl-strip-spring.jpg",
  },
  {
    id: "summer",
    name: "Summer Terrace",
    edition: "Summer Edition",
    tagline: "Warm evenings, festivals and long escapes.",
    description: "Eight relaxed conversations for the brightest, longest days.",
    accent: "#2c7a72",
    icon: "☀",
    image: "/ssl/ssl-season-summer.jpg",
    strip: "/ssl/ssl-strip-summer.jpg",
  },
  {
    id: "fall",
    name: "Fall Lounge",
    edition: "Fall Edition",
    tagline: "Cozy evenings, gatherings and gratitude.",
    description: "Eight warming conversations for slower, richer moments.",
    accent: "#b5794a",
    icon: "🍁",
    image: "/ssl/ssl-season-fall.jpg",
    strip: "/ssl/ssl-strip-autumn.jpg",
  },
  {
    id: "winter",
    name: "Winter Bar",
    edition: "Winter Edition",
    tagline: "Colder days and warmer connections.",
    description: "Eight conversations for colder days and warmer connections.",
    accent: "#5b8fa8",
    icon: "❄",
    image: "/ssl/ssl-season-winter.jpg",
    strip: "/ssl/ssl-strip-winter.jpg",
  },
];

export const SEASON_MAP = Object.fromEntries(SEASONS.map((s) => [s.id, s]));

// ─────────────────────────────────────────────────────────────────────────
// SPRING CAFÉ
// ─────────────────────────────────────────────────────────────────────────
const SPRING = [
  {
    id: "spring-1", n: 1, theme: "Fresh Starts & Introductions",
    setting: "A bright café patio on a spring morning.",
    objective: "Introduce yourself to someone new and ask about the neighbourhood.",
    dialogue: [
      { speaker: "Alex", line: "Hi, is this seat taken?" },
      { speaker: "Sam",  line: "No, go ahead! I'm Sam, by the way." },
      { speaker: "Alex", line: "Nice to meet you, Sam. I'm Alex. I just moved to the neighbourhood." },
      { speaker: "Sam",  line: "Oh, welcome! How are you liking it so far?" },
      { speaker: "Alex", line: "It's great. The weather has been perfect for exploring." },
    ],
    cocktail: { name: "Spring Breeze Mimosa", ingredients: "Prosecco · Orange juice · Splash of cranberry", note: "A classic brunch favourite — perfect for celebrating a fresh start on a sunny spring morning." },
    mocktail: { name: "Sunrise Sparkler", ingredients: "Sparkling water · Orange juice · Cranberry · Orange slice", note: "Refreshing and festive — all the colour and sparkle, none of the alcohol." },
    keyPhrases: ["Is this seat taken?", "I just moved to...", "The weather has been perfect for...", "I'm [Name], by the way.", "How are you liking it so far?", "Nice to meet you."],
    pairQuestions: ["How do you usually introduce yourself to new people?", "What is your favourite thing about spring?"],
    rolePlay: "You are at a café. Introduce yourself and ask about the neighbourhood.",
    mixAndSpeak: ["I'll have a Spring Breeze Mimosa, please.", "Could I get the Sunrise Sparkler?", "What do you recommend for a sunny day?"],
    levels: { beginner: "What is your name and where are you from?", intermediate: "Tell me about a time you started something new.", advanced: "How do changing seasons affect people's moods and social habits?" },
    reflection: "What did you learn today?",
  },
  {
    id: "spring-2", n: 2, theme: "Hobbies & Free Time",
    setting: "A casual after-work gathering at a bar.",
    objective: "Discuss your hobbies and suggest an activity you could do together.",
    dialogue: [
      { speaker: "Jordan", line: "What are you into lately?" },
      { speaker: "Taylor", line: "I've been trying my hand at gardening. It's so relaxing." },
      { speaker: "Jordan", line: "That sounds nice. I'm thinking of taking up cycling now that it's warmer." },
      { speaker: "Taylor", line: "You should! We could go for a ride sometime." },
    ],
    cocktail: { name: "Garden Gin & Tonic", ingredients: "Gin · Tonic water · Cucumber slices · Fresh mint", note: "Crisp and herbaceous — ideal for relaxing after a day spent outdoors or in the garden." },
    mocktail: { name: "Cucumber Mint Cooler", ingredients: "Sparkling water · Muddled cucumber · Fresh mint · Lime juice", note: "Hydrating and light — perfect for cooling down after an outdoor hobby." },
    keyPhrases: ["What are you into lately?", "I'm thinking of...", "You should!", "I've been trying...", "That sounds nice.", "We could [do something] sometime."],
    pairQuestions: ["What do you like to do in your free time?", "Is there a new hobby you want to try this spring?"],
    rolePlay: "Discuss your hobbies and suggest an activity you could do together.",
    mixAndSpeak: ["I'm looking for something refreshing.", "Does this have a strong mint flavour?", "I'll take the Garden G&T — it sounds crisp."],
    levels: { beginner: "What is your favourite hobby?", intermediate: "How do you balance free time with work or studies?", advanced: "Why do you think having hobbies is important for adults?" },
    reflection: "What did you learn today?",
  },
  {
    id: "spring-3", n: 3, theme: "Travel Plans",
    setting: "Planning a trip over drinks at a café.",
    objective: "Ask about your partner's travel plans and share your own dream vacation.",
    dialogue: [
      { speaker: "Casey",  line: "Do you have any travel plans coming up?" },
      { speaker: "Morgan", line: "Actually, yes! I'm heading to the coast next month." },
      { speaker: "Casey",  line: "Oh, I'm so jealous. I haven't booked anything yet." },
      { speaker: "Morgan", line: "You should look into it. Flights are pretty cheap right now." },
    ],
    cocktail: { name: "Tropical Spring Punch", ingredients: "Light rum · Pineapple juice · Lime juice · Grenadine", note: "A fruity, sun-soaked drink that brings a taste of a tropical getaway right to your glass." },
    mocktail: { name: "Island Breeze", ingredients: "Pineapple juice · Orange juice · Grenadine · Soda water", note: "Sweet and vibrant — vacation vibes in every sip, no passport required." },
    keyPhrases: ["Do you have any travel plans coming up?", "I'm so jealous.", "You should look into it.", "I'm heading to...", "I haven't booked anything yet.", "Flights are pretty cheap right now."],
    pairQuestions: ["Where is your dream travel destination?", "Do you prefer beach holidays or city tours?"],
    rolePlay: "Ask about your partner's travel plans and share your own dream vacation ideas.",
    mixAndSpeak: ["If you like fruity drinks, try the Tropical Punch.", "Something light, please.", "I'll have what they're having."],
    levels: { beginner: "Where do you want to travel?", intermediate: "Describe the best trip you have ever taken.", advanced: "How does travelling change our perspective on the world?" },
    reflection: "What did you learn today?",
  },
  {
    id: "spring-4", n: 4, theme: "Food & Dining",
    setting: "Looking at a menu in a spring restaurant.",
    objective: "Discuss the menu and decide what to order together.",
    dialogue: [
      { speaker: "Riley", line: "Everything looks so good. What are you getting?" },
      { speaker: "Jamie", line: "I'm torn between the spring salad and the grilled chicken." },
      { speaker: "Riley", line: "The salad sounds really fresh. I think I'll go with the pasta." },
      { speaker: "Jamie", line: "Good choice. Let's get some appetisers to share, too." },
    ],
    cocktail: { name: "Strawberry Basil Smash", ingredients: "Vodka · Fresh strawberries · Basil · Lemon juice · Simple syrup", note: "Sweet berries meet savoury herbs — a drink that perfectly captures the essence of spring dining." },
    mocktail: { name: "Berry Basil Lemonade", ingredients: "Lemonade · Muddled strawberries · Fresh basil", note: "Sweet, tangy, and herbaceous — pairs beautifully with any light spring meal." },
    keyPhrases: ["What are you getting?", "That sounds really fresh.", "Let's get some [food] to share.", "I'm torn between...", "I think I'll go with...", "Good choice."],
    pairQuestions: ["What is your favourite type of food?", "Do you prefer cooking at home or eating out?"],
    rolePlay: "You are at a restaurant. Discuss the menu and decide what to order together.",
    mixAndSpeak: ["Can I get that, but not too sweet?", "I'd love the Berry Basil Lemonade.", "What pairs well with a light salad?"],
    levels: { beginner: "What did you eat for dinner yesterday?", intermediate: "How do seasonal ingredients change the way you cook or eat?", advanced: "Discuss the cultural significance of sharing a meal in your country." },
    reflection: "What did you learn today?",
  },
  {
    id: "spring-5", n: 5, theme: "Weekend Stories",
    setting: "Monday evening at a local bar.",
    objective: "Ask about your partner's weekend and share a recent story.",
    dialogue: [
      { speaker: "Drew",   line: "How was your weekend?" },
      { speaker: "Harper", line: "It was pretty low-key. I just caught up on some reading and relaxed. You?" },
      { speaker: "Drew",   line: "I ended up going to that new outdoor market. It was packed!" },
      { speaker: "Harper", line: "Oh, I've been meaning to check that out. Was it good?" },
    ],
    cocktail: { name: "Sunday Morning Paloma", ingredients: "Tequila · Grapefruit juice · Lime juice · Soda water · Salt rim", note: "Bright and citrusy — perfect for a lazy Sunday afternoon catch-up with friends." },
    mocktail: { name: "Grapefruit Fizz", ingredients: "Grapefruit juice · Lime juice · Soda water · Agave syrup", note: "Tart and bubbly — a great pick-me-up for sharing weekend tales." },
    keyPhrases: ["How was your weekend?", "I ended up going to...", "I've been meaning to check that out.", "It was pretty low-key.", "It was packed!", "Was it good?"],
    pairQuestions: ["What is your ideal weekend?", "Do you prefer busy weekends or relaxing ones?"],
    rolePlay: "Ask about your partner's weekend and share a story about something interesting you did recently.",
    mixAndSpeak: ["I'll grab a Paloma, please.", "Could I get a Grapefruit Fizz?", "Make it two, please."],
    levels: { beginner: "What did you do last weekend?", intermediate: "Tell a story about a memorable weekend trip you took.", advanced: "Why is the concept of the \"weekend\" so important in modern society?" },
    reflection: "What did you learn today?",
  },
  {
    id: "spring-6", n: 6, theme: "Goals & Motivation",
    setting: "A coffee shop working session.",
    objective: "Discuss a personal goal and brainstorm ways to achieve it together.",
    dialogue: [
      { speaker: "Quinn", line: "I really need to get organised this month." },
      { speaker: "Avery", line: "Me too. I've set a goal to read one book a week." },
      { speaker: "Quinn", line: "That's ambitious! How are you staying motivated?" },
      { speaker: "Avery", line: "I joined a book club. Having people to talk to keeps me on track." },
    ],
    cocktail: { name: "The Motivator (Espresso Martini)", ingredients: "Vodka · Espresso · Coffee liqueur · Simple syrup", note: "A sophisticated, energising classic — the perfect drink to fuel an ambitious conversation." },
    mocktail: { name: "Vanilla Cold Brew Tonic", ingredients: "Cold brew coffee · Tonic water · Vanilla syrup", note: "Modern and bubbly — keeps you sharp and focused without the alcohol." },
    keyPhrases: ["I really need to get organised.", "That's ambitious!", "It keeps me on track.", "I've set a goal to...", "How are you staying motivated?", "Having people to talk to..."],
    pairQuestions: ["What is one goal you have for this spring?", "How do you stay motivated when things get difficult?"],
    rolePlay: "Discuss a personal goal and brainstorm ways to achieve it together.",
    mixAndSpeak: ["I need a pick-me-up. I'll have the Espresso Martini.", "Can I get the Vanilla Cold Brew Tonic?", "Something with caffeine, please."],
    levels: { beginner: "What do you want to learn this year?", intermediate: "Describe a time when you achieved a difficult goal.", advanced: "How do societal expectations influence the goals we set for ourselves?" },
    reflection: "What did you learn today?",
  },
  {
    id: "spring-7", n: 7, theme: "Social Situations",
    setting: "A crowded spring party.",
    objective: "Approach someone you don't know and start a conversation.",
    dialogue: [
      { speaker: "Blake",   line: "It's pretty loud in here, isn't it?" },
      { speaker: "Charlie", line: "Yeah, it's a great turnout though. Do you know many people here?" },
      { speaker: "Blake",   line: "Just a few from work. How about you?" },
      { speaker: "Charlie", line: "I came with a friend, but they wandered off. I'm Charlie, by the way." },
    ],
    cocktail: { name: "Classic Margarita", ingredients: "Tequila · Triple sec · Lime juice · Salt rim", note: "The ultimate social drink — perfect for breaking the ice at any gathering or party." },
    mocktail: { name: "Virgin Margarita", ingredients: "Lime juice · Orange juice · Agave syrup · Sparkling water · Salt rim", note: "All the fun and flavour of the classic — keeps you sharp for networking." },
    keyPhrases: ["It's pretty loud in here, isn't it?", "Do you know many people here?", "I came with a friend.", "It's a great turnout.", "Just a few from work.", "They wandered off."],
    pairQuestions: ["Do you enjoy large parties or small gatherings?", "How do you usually start a conversation with a stranger?"],
    rolePlay: "Imagine you are at a networking event. Approach someone you don't know and start a conversation.",
    mixAndSpeak: ["Excuse me, can I get a Classic Margarita?", "I'll have the Virgin Margarita, please.", "Can we start a tab?"],
    levels: { beginner: "Do you like parties? Why or why not?", intermediate: "What makes a social event successful in your opinion?", advanced: "Discuss differences between socialising in your home country versus abroad." },
    reflection: "What did you learn today?",
  },
  {
    id: "spring-8", n: 8, theme: "Celebrations",
    setting: "A celebratory dinner with friends.",
    objective: "Propose a toast to a recent accomplishment.",
    dialogue: [
      { speaker: "Skyler", line: "I can't believe we finally finished the project!" },
      { speaker: "Parker", line: "I know! It feels so good to be done. We should celebrate." },
      { speaker: "Skyler", line: "Absolutely. Let's order some drinks." },
      { speaker: "Parker", line: "Here's to us! Cheers!" },
    ],
    cocktail: { name: "French 75", ingredients: "Gin · Lemon juice · Simple syrup · Champagne", note: "Elegant and effervescent — the gold standard for sophisticated celebrations the world over." },
    mocktail: { name: "Sparkling Lemon Elderflower", ingredients: "Elderflower cordial · Lemon juice · Sparkling water", note: "Floral and fizzy — a beautiful drink for raising a glass without the alcohol." },
    keyPhrases: ["I can't believe we finally...", "We should celebrate.", "Here's to us!", "It feels so good to be done.", "Let's order some drinks.", "Cheers!"],
    pairQuestions: ["What is something you are proud of achieving recently?", "How do you usually celebrate special occasions?"],
    rolePlay: "Propose a toast to your partner for a recent accomplishment — or for completing this course!",
    mixAndSpeak: ["I'll have a French 75 to celebrate.", "A Sparkling Elderflower for me, please.", "What are we toasting to?"],
    levels: { beginner: "When is your birthday? How do you celebrate?", intermediate: "Describe the best party or celebration you have ever attended.", advanced: "Why are rituals of celebration important in human culture?" },
    reflection: "What did you learn today?",
  },
];

// ─────────────────────────────────────────────────────────────────────────
// SUMMER TERRACE
// ─────────────────────────────────────────────────────────────────────────
const SUMMER = [
  {
    id: "summer-1", n: 1, theme: "Summer Arrivals & Plans",
    setting: "A rooftop terrace on the first warm evening of summer.",
    objective: "Meet someone at a summer event, introduce yourself and compare plans.",
    dialogue: [
      { speaker: "Alex", line: "It finally feels like summer, doesn't it?" },
      { speaker: "Sam",  line: "Definitely. Have you made any plans yet?" },
      { speaker: "Alex", line: "A few. I'm hoping to spend more time outdoors." },
      { speaker: "Sam",  line: "Same here. We should plan something together." },
    ],
    cocktail: { name: "Citrus Sunset Spritz", ingredients: "Aperol · Prosecco · Soda water · Orange", note: "Bright, sparkling and easy-going — a relaxed way to welcome the season." },
    mocktail: { name: "Sunset Citrus Fizz", ingredients: "Orange · Pink grapefruit · Soda water · Rosemary", note: "Colourful and refreshing, with all the sunset glow and none of the alcohol." },
    keyPhrases: ["It finally feels like...", "Have you made any plans yet?", "I'm hoping to...", "Same here.", "We should plan...", "That sounds like a great start."],
    pairQuestions: ["What are you looking forward to this summer?", "Do you prefer busy summers or relaxing ones?"],
    rolePlay: "Meet someone at a summer event. Introduce yourself and compare your plans.",
    mixAndSpeak: ["I'll start with the Citrus Sunset Spritz.", "Could I have the Sunset Citrus Fizz?", "What would you recommend for a warm evening?"],
    levels: { beginner: "What do you like about summer?", intermediate: "Describe your ideal summer day.", advanced: "How does summer change the way people socialise in your country?" },
    reflection: "What useful phrase did you use today?",
  },
  {
    id: "summer-2", n: 2, theme: "Outdoor Activities",
    setting: "Friends relaxing after an outdoor activity.",
    objective: "Suggest an outdoor activity, agree on a time and discuss what to bring.",
    dialogue: [
      { speaker: "Jordan", line: "What do you usually do when the weather is this good?" },
      { speaker: "Taylor", line: "I try to get outside. I've been going for evening walks lately." },
      { speaker: "Jordan", line: "Nice. Would you be up for kayaking sometime?" },
      { speaker: "Taylor", line: "Absolutely. I've always wanted to try it." },
    ],
    cocktail: { name: "Cucumber Collins", ingredients: "Gin · Lemon · Cucumber · Soda water", note: "Cool, crisp and made for an evening after the park, pool or trail." },
    mocktail: { name: "Cucumber Lime Cooler", ingredients: "Cucumber · Lime · Mint · Sparkling water", note: "Light and hydrating — a clean, garden-fresh summer cooler." },
    keyPhrases: ["What do you usually do when...?", "I try to get outside.", "I've been ... lately.", "Would you be up for...?", "I've always wanted to try it.", "Absolutely."],
    pairQuestions: ["Which outdoor activities do you enjoy?", "What summer activity would you like to try?"],
    rolePlay: "Suggest an outdoor activity, agree on a time and discuss what to bring.",
    mixAndSpeak: ["I'm looking for something really refreshing.", "Does this have a strong cucumber flavour?", "I'll take the cooler — it sounds light."],
    levels: { beginner: "Do you like being outdoors?", intermediate: "How do you stay active during hot weather?", advanced: "Should cities invest more in outdoor public spaces? Why?" },
    reflection: "What useful phrase did you use today?",
  },
  {
    id: "summer-3", n: 3, theme: "Summer Travel",
    setting: "Two friends comparing holiday ideas at a café.",
    objective: "Compare two destinations and decide which offers the better trip.",
    dialogue: [
      { speaker: "Casey",  line: "Are you getting away anywhere this summer?" },
      { speaker: "Morgan", line: "I'm thinking about a few days by the sea." },
      { speaker: "Casey",  line: "That sounds perfect. Have you booked anything?" },
      { speaker: "Morgan", line: "Not yet. I'm still weighing up my options." },
    ],
    cocktail: { name: "Blue Lagoon Highball", ingredients: "Vodka · Blue curaçao · Lemon · Soda water", note: "Cool and vivid, inspired by clear water and a long summer escape." },
    mocktail: { name: "Ocean Blue Lemonade", ingredients: "Blue citrus syrup · Lemon · Soda water", note: "A bright alcohol-free holiday in a glass — tart, bubbly and fun." },
    keyPhrases: ["Are you getting away anywhere?", "I'm thinking about...", "That sounds perfect.", "Have you booked anything?", "Not yet.", "I'm weighing up my options."],
    pairQuestions: ["Where would you go for a short summer break?", "Do you plan every detail or travel spontaneously?"],
    rolePlay: "Compare two destinations and decide which one offers the better trip.",
    mixAndSpeak: ["If you like citrus, try the Blue Lagoon.", "Something sparkling, please.", "Could you make that alcohol-free?"],
    levels: { beginner: "Where do you want to travel?", intermediate: "Describe a memorable summer holiday.", advanced: "How can popular destinations balance tourism and local life?" },
    reflection: "What useful phrase did you use today?",
  },
  {
    id: "summer-4", n: 4, theme: "Summer Food & Dining",
    setting: "Looking at a menu on a shaded terrace.",
    objective: "Discuss the menu, ask about ingredients and choose dishes to share.",
    dialogue: [
      { speaker: "Riley", line: "I can't decide. Everything looks so fresh." },
      { speaker: "Jamie", line: "I'm leaning towards the grilled fish. How about you?" },
      { speaker: "Riley", line: "The chilled noodles sound good, but I might get the tacos." },
      { speaker: "Jamie", line: "Let's order both and share." },
    ],
    cocktail: { name: "Watermelon Mojito", ingredients: "White rum · Watermelon · Mint · Lime", note: "Juicy, cool and lively — a natural match for relaxed summer dining." },
    mocktail: { name: "Watermelon Mint Soda", ingredients: "Watermelon · Mint · Lime · Soda water", note: "Fresh fruit, bright lime and bubbles for a simple seasonal favourite." },
    keyPhrases: ["I can't decide.", "I'm leaning towards...", "How about you?", "I might get...", "Let's order both and share.", "That sounds refreshing."],
    pairQuestions: ["Which foods do you enjoy in hot weather?", "What is a favourite summer dish from your country?"],
    rolePlay: "Discuss the menu, ask about ingredients and choose dishes to share.",
    mixAndSpeak: ["Can I get that without coriander?", "Is the watermelon drink very sweet?", "What pairs well with the grilled fish?"],
    levels: { beginner: "What do you eat in summer?", intermediate: "Describe a perfect outdoor meal.", advanced: "How do climate and culture shape seasonal food traditions?" },
    reflection: "What useful phrase did you use today?",
  },
  {
    id: "summer-5", n: 5, theme: "Weekend Adventures",
    setting: "Sunday evening at a neighbourhood bar.",
    objective: "Tell a short weekend story and answer follow-up questions.",
    dialogue: [
      { speaker: "Drew",   line: "You look tired. Busy weekend?" },
      { speaker: "Harper", line: "Very. We took a last-minute trip to the mountains." },
      { speaker: "Drew",   line: "No way! How did that come about?" },
      { speaker: "Harper", line: "A friend invited us, so we just went for it." },
    ],
    cocktail: { name: "Peach Bourbon Smash", ingredients: "Bourbon · Peach · Lemon · Mint", note: "Ripe fruit and a smooth finish — made for swapping weekend stories." },
    mocktail: { name: "Peach Iced Tea Fizz", ingredients: "Peach · Black tea · Lemon · Soda water", note: "Fruity, gently bitter and sparkling — an easy afternoon pick-me-up." },
    keyPhrases: ["Busy weekend?", "We took a last-minute trip.", "No way!", "How did that come about?", "We just went for it.", "It was worth it."],
    pairQuestions: ["What did you do last weekend?", "Do you enjoy last-minute plans? Why or why not?"],
    rolePlay: "Tell a short weekend story. Your partner asks follow-up questions.",
    mixAndSpeak: ["I'll have a Peach Bourbon Smash, please.", "Could I get the iced tea fizz?", "Make it two, please."],
    levels: { beginner: "What was the best part of your weekend?", intermediate: "Tell a story about an unexpected adventure.", advanced: "Why do shared experiences often become our strongest memories?" },
    reflection: "What useful phrase did you use today?",
  },
  {
    id: "summer-6", n: 6, theme: "Staying Cool & Healthy",
    setting: "A café during a particularly hot afternoon.",
    objective: "Share one summer problem and offer practical, supportive advice.",
    dialogue: [
      { speaker: "Quinn", line: "This heat is really draining my energy." },
      { speaker: "Avery", line: "Same. I've started exercising early in the morning." },
      { speaker: "Quinn", line: "That's sensible. How else are you coping with it?" },
      { speaker: "Avery", line: "Plenty of water, lighter meals and more breaks." },
    ],
    cocktail: { name: "Shiso Gin Rickey", ingredients: "Gin · Lime · Shiso · Soda water", note: "Herbal, dry and crisp — a Japanese-inspired drink for humid nights." },
    mocktail: { name: "Shiso Lime Sparkler", ingredients: "Shiso · Lime · Honey · Sparkling water", note: "Clean, tart and aromatic — refreshment without feeling heavy." },
    keyPhrases: ["This heat is draining my energy.", "I've started...", "That's sensible.", "How are you coping with it?", "I've been making sure to...", "It makes a big difference."],
    pairQuestions: ["How does hot weather affect your routine?", "What helps you feel comfortable and energised?"],
    rolePlay: "Share one summer problem and offer practical, supportive advice.",
    mixAndSpeak: ["Could I have extra ice, please?", "Is there anything light and not too sweet?", "I'll have the shiso sparkler."],
    levels: { beginner: "How do you stay cool?", intermediate: "Explain your healthiest summer habit.", advanced: "How should communities prepare for increasingly hot summers?" },
    reflection: "What useful phrase did you use today?",
  },
  {
    id: "summer-7", n: 7, theme: "Festivals & Social Events",
    setting: "A lantern-lit summer festival with friends.",
    objective: "Meet at a festival, decide what to do first and arrange a meeting point.",
    dialogue: [
      { speaker: "Blake",   line: "It's busier than I expected tonight." },
      { speaker: "Charlie", line: "I know! The atmosphere is amazing though." },
      { speaker: "Blake",   line: "Do you want to find some food before the fireworks?" },
      { speaker: "Charlie", line: "Good idea. Let's see what they have." },
    ],
    cocktail: { name: "Yuzu Highball", ingredients: "Whisky · Yuzu · Soda water · Lemon peel", note: "Citrusy and crisp — a lively companion for a summer night out." },
    mocktail: { name: "Yuzu Ginger Fizz", ingredients: "Yuzu · Ginger · Honey · Sparkling water", note: "Bright, gently spicy and festive, with a refreshing clean finish." },
    keyPhrases: ["It's busier than I expected.", "The atmosphere is amazing.", "Do you want to...?", "Good idea.", "Let's see what they have.", "Shall we find somewhere quieter?"],
    pairQuestions: ["Which festivals or events do you enjoy?", "Do you prefer large crowds or small gatherings?"],
    rolePlay: "Meet at a festival, decide what to do first and arrange a meeting point.",
    mixAndSpeak: ["Excuse me, could I get a Yuzu Highball?", "One Yuzu Ginger Fizz, please.", "Can we start a tab?"],
    levels: { beginner: "Do you like festivals?", intermediate: "Describe the atmosphere at a special event.", advanced: "Why are public festivals important to a community's identity?" },
    reflection: "What useful phrase did you use today?",
  },
  {
    id: "summer-8", n: 8, theme: "Summer Memories & Next Steps",
    setting: "Friends looking back on the season over dinner.",
    objective: "Share a highlight, ask follow-up questions and propose a future plan.",
    dialogue: [
      { speaker: "Skyler", line: "I can't believe summer is nearly over." },
      { speaker: "Parker", line: "It went quickly. What was your highlight?" },
      { speaker: "Skyler", line: "Probably our weekend by the sea. How about yours?" },
      { speaker: "Parker", line: "The festival. I'd love to do that again next year." },
    ],
    cocktail: { name: "Pineapple Rum Punch", ingredients: "Dark rum · Pineapple · Lime · Bitters", note: "Tropical, celebratory and full of flavour — a final toast to summer." },
    mocktail: { name: "Pineapple Coconut Cooler", ingredients: "Pineapple · Coconut water · Lime · Soda", note: "Smooth, sunny and alcohol-free — a refreshing finish to the course." },
    keyPhrases: ["I can't believe...", "It went quickly.", "What was your highlight?", "Probably...", "How about yours?", "I'd love to do that again."],
    pairQuestions: ["What has been your favourite summer memory?", "What would you like to do before summer ends?"],
    rolePlay: "Share a highlight, ask follow-up questions and propose a future plan.",
    mixAndSpeak: ["I'll have the rum punch to celebrate.", "A Pineapple Coconut Cooler for me.", "Here's to a wonderful summer!"],
    levels: { beginner: "What did you enjoy this summer?", intermediate: "Describe a summer memory you want to keep.", advanced: "How do seasonal experiences influence our sense of time and identity?" },
    reflection: "What useful phrase did you use today?",
  },
];

// ─────────────────────────────────────────────────────────────────────────
// FALL LOUNGE
// ─────────────────────────────────────────────────────────────────────────
const FALL = [
  {
    id: "fall-1", n: 1, theme: "Seasonal Changes & New Routines",
    setting: "Two friends meeting after the first noticeably cool day.",
    objective: "Meet a friend after summer and compare the routines you want to restart.",
    dialogue: [
      { speaker: "Alex", line: "There's definitely a chill in the air tonight." },
      { speaker: "Sam",  line: "I know. It feels like fall arrived overnight." },
      { speaker: "Alex", line: "I've started getting back into my evening walks." },
      { speaker: "Sam",  line: "Me too. This weather makes routines feel easier somehow." },
    ],
    cocktail: { name: "Spiced Apple Spritz", ingredients: "Apple brandy · Prosecco · Cinnamon · Soda", note: "Crisp apple, warm spice and bubbles — a bright welcome to the new season." },
    mocktail: { name: "Apple Rosemary Fizz", ingredients: "Apple · Rosemary · Lemon · Sparkling water", note: "Fresh, fragrant and gently herbal, with all the feeling of a cool fall evening." },
    keyPhrases: ["There's a chill in the air.", "It feels like fall arrived overnight.", "I've started getting back into...", "Me too.", "This weather makes ... feel easier.", "It feels like the right time to..."],
    pairQuestions: ["What changes do you notice when fall begins?", "Does your daily routine change with the season?"],
    rolePlay: "Meet a friend after summer and compare the routines you want to restart.",
    mixAndSpeak: ["I'll start with the Spiced Apple Spritz.", "Could I have the Apple Rosemary Fizz?", "What would you recommend for a cool evening?"],
    levels: { beginner: "What do you like about fall?", intermediate: "Describe how your routine changes in fall.", advanced: "Why do seasonal changes influence our mood and motivation?" },
    reflection: "What useful phrase did you use today?",
  },
  {
    id: "fall-2", n: 2, theme: "Hobbies & Cozy Evenings",
    setting: "Friends talking in a quiet lounge after work.",
    objective: "Discuss relaxing hobbies and suggest something you could try together.",
    dialogue: [
      { speaker: "Jordan", line: "What have you been doing with your evenings lately?" },
      { speaker: "Taylor", line: "I've gotten back into reading. It's become my way to unwind." },
      { speaker: "Jordan", line: "That sounds nice. I've been meaning to cook more." },
      { speaker: "Taylor", line: "You should. We could try a new recipe together." },
    ],
    cocktail: { name: "Maple Old Fashioned", ingredients: "Bourbon · Maple · Bitters · Orange peel", note: "Smooth, warming and slow-sipping — made for an unhurried evening indoors." },
    mocktail: { name: "Maple Ginger Warmer", ingredients: "Apple · Ginger · Maple · Lemon", note: "Comforting spice and gentle sweetness in a warming alcohol-free drink." },
    keyPhrases: ["What have you been doing lately?", "I've gotten back into...", "It's my way to unwind.", "I've been meaning to...", "You should.", "We could try ... together."],
    pairQuestions: ["How do you like to spend a quiet evening?", "Is there a hobby you want to return to?"],
    rolePlay: "Discuss relaxing hobbies and suggest something you could try together.",
    mixAndSpeak: ["I'm looking for something warming.", "Is the maple flavour very strong?", "I'll take the ginger warmer, please."],
    levels: { beginner: "What is your favourite indoor hobby?", intermediate: "How do hobbies help you manage stress?", advanced: "Has modern technology improved or weakened our ability to relax?" },
    reflection: "What useful phrase did you use today?",
  },
  {
    id: "fall-3", n: 3, theme: "Weekend Getaways & Autumn Views",
    setting: "Two friends planning a short fall escape.",
    objective: "Compare two destinations and choose one for a weekend getaway.",
    dialogue: [
      { speaker: "Casey",  line: "Have you thought about taking a trip this fall?" },
      { speaker: "Morgan", line: "Actually, yes. I'd love to see the leaves in the mountains." },
      { speaker: "Casey",  line: "That would be beautiful. Is anywhere in particular on your list?" },
      { speaker: "Morgan", line: "Maybe Takayama. I'm still looking into it." },
    ],
    cocktail: { name: "Cranberry Gin Fizz", ingredients: "Gin · Cranberry · Lemon · Soda water", note: "Tart, bright and sparkling — perfect after a day exploring autumn scenery." },
    mocktail: { name: "Cranberry Orange Sparkler", ingredients: "Cranberry · Orange · Rosemary · Soda", note: "Colourful and refreshing, with a festive balance of fruit and herbs." },
    keyPhrases: ["Have you thought about...?", "I'd love to...", "That would be beautiful.", "Anywhere in particular?", "It's on my list.", "I'm still looking into it."],
    pairQuestions: ["Where would you go for a fall weekend?", "Do you travel for scenery, food or activities?"],
    rolePlay: "Compare two destinations and choose one for a weekend getaway.",
    mixAndSpeak: ["If you like tart drinks, try the Cranberry Fizz.", "Something fruity but light, please.", "Could you make that alcohol-free?"],
    levels: { beginner: "Where do you want to go?", intermediate: "Describe a memorable scenic trip.", advanced: "How can seasonal tourism benefit and challenge local communities?" },
    reflection: "What useful phrase did you use today?",
  },
  {
    id: "fall-4", n: 4, theme: "Comfort Food & Dining",
    setting: "Looking at a seasonal menu in a cozy restaurant.",
    objective: "Discuss a seasonal menu, ask about ingredients and decide what to order.",
    dialogue: [
      { speaker: "Riley", line: "Everything on the seasonal menu sounds good." },
      { speaker: "Jamie", line: "I know. I'm torn between the stew and the mushroom pasta." },
      { speaker: "Riley", line: "The pasta sounds tempting, but I might go for the roast chicken." },
      { speaker: "Jamie", line: "Good choice. Shall we get something to share first?" },
    ],
    cocktail: { name: "Pear & Sage Martini", ingredients: "Vodka · Pear · Lemon · Fresh sage", note: "Elegant fruit and earthy herbs — a natural partner for a comforting meal." },
    mocktail: { name: "Pear Sage Cooler", ingredients: "Pear · Sage · Lemon · Sparkling water", note: "Light, aromatic and balanced, with a clean seasonal finish." },
    keyPhrases: ["Everything sounds good.", "I'm torn between...", "That sounds tempting.", "I might go for...", "Good choice.", "Shall we get something to share?"],
    pairQuestions: ["Which foods feel comforting to you?", "What seasonal ingredient do you look forward to?"],
    rolePlay: "Discuss a seasonal menu, ask about ingredients and decide what to order.",
    mixAndSpeak: ["Could I get that without mushrooms?", "Is the pear drink very sweet?", "What pairs well with the roast chicken?"],
    levels: { beginner: "What is your favourite comfort food?", intermediate: "Describe a meal connected to a happy memory.", advanced: "Why does food play such a strong role in memory and identity?" },
    reflection: "What useful phrase did you use today?",
  },
  {
    id: "fall-5", n: 5, theme: "Autumn Stories & Traditions",
    setting: "Friends comparing seasonal traditions over drinks.",
    objective: "Share a childhood seasonal memory and ask follow-up questions.",
    dialogue: [
      { speaker: "Drew",   line: "Did your family have any special fall traditions?" },
      { speaker: "Harper", line: "We always went apple picking when I was young." },
      { speaker: "Drew",   line: "That must bring back memories." },
      { speaker: "Harper", line: "It does. I can still remember the smell of the orchard." },
    ],
    cocktail: { name: "Autumn Sangria", ingredients: "Red wine · Apple · Orange · Cinnamon", note: "Fruity, spiced and made for sharing stories around the table." },
    mocktail: { name: "Spiced Grape Punch", ingredients: "Grape · Apple · Orange · Cinnamon", note: "Rich fruit and gentle spice in a festive alcohol-free punch." },
    keyPhrases: ["Did your family ever...?", "When I was young...", "That must bring back memories.", "It does.", "I can still remember...", "We used to..."],
    pairQuestions: ["What seasonal tradition do you remember?", "Which traditions would you like to continue?"],
    rolePlay: "Share a childhood seasonal memory and ask your partner follow-up questions.",
    mixAndSpeak: ["We'll share a jug of the Autumn Sangria.", "Could I get the grape punch?", "Make it two, please."],
    levels: { beginner: "What did you do in fall as a child?", intermediate: "Tell a story connected to a family tradition.", advanced: "How do traditions change when people move between cultures?" },
    reflection: "What useful phrase did you use today?",
  },
  {
    id: "fall-6", n: 6, theme: "Goals & Getting Back on Track",
    setting: "A café working session at the start of a busy month.",
    objective: "Share a goal, identify the first step and agree how to stay accountable.",
    dialogue: [
      { speaker: "Quinn", line: "I need to get back on track after the summer." },
      { speaker: "Avery", line: "Same here. What's your main priority this month?" },
      { speaker: "Quinn", line: "I want to finish a project I've been putting off." },
      { speaker: "Avery", line: "Breaking it into smaller steps might help." },
    ],
    cocktail: { name: "Espresso Maple Martini", ingredients: "Vodka · Espresso · Maple · Coffee liqueur", note: "Bold, smooth and energising — a sophisticated drink for ambitious conversation." },
    mocktail: { name: "Maple Cold Brew Tonic", ingredients: "Cold brew · Tonic water · Maple · Orange", note: "Bubbly coffee with gentle sweetness to keep the conversation focused." },
    keyPhrases: ["I need to get back on track.", "What's your main priority?", "I've been putting it off.", "Breaking it into steps might help.", "I'm aiming to...", "That feels manageable."],
    pairQuestions: ["What is one priority you have this season?", "What helps you restart after losing momentum?"],
    rolePlay: "Share a goal, identify the first step and agree on a way to stay accountable.",
    mixAndSpeak: ["I need a pick-me-up.", "Could I get the Maple Cold Brew Tonic?", "Something with coffee, please."],
    levels: { beginner: "What do you want to finish?", intermediate: "Describe how you recovered from a setback.", advanced: "How does productivity culture influence the goals we set?" },
    reflection: "What useful phrase did you use today?",
  },
  {
    id: "fall-7", n: 7, theme: "Gatherings & Invitations",
    setting: "Friends arranging a casual dinner gathering.",
    objective: "Invite your partner to a gathering and discuss the time, food and what to bring.",
    dialogue: [
      { speaker: "Blake",   line: "I'm thinking of having a few people over next Saturday." },
      { speaker: "Charlie", line: "That sounds fun. Do you want me to bring anything?" },
      { speaker: "Blake",   line: "Maybe something for dessert, if you don't mind." },
      { speaker: "Charlie", line: "Of course. I'll see what I can make." },
    ],
    cocktail: { name: "Fig Bourbon Sour", ingredients: "Bourbon · Fig · Lemon · Simple syrup", note: "Rich fruit and bright citrus — a welcoming drink for a relaxed gathering." },
    mocktail: { name: "Fig Lemon Sour", ingredients: "Fig · Lemon · Black tea · Soda water", note: "Tangy, softly sweet and layered enough for a special occasion." },
    keyPhrases: ["I'm thinking of having people over.", "That sounds fun.", "Should I bring anything?", "If you don't mind.", "Of course.", "I'll see what I can do."],
    pairQuestions: ["Do you enjoy hosting people at home?", "What makes a gathering feel comfortable?"],
    rolePlay: "Invite your partner to a gathering and discuss the time, food and what to bring.",
    mixAndSpeak: ["Excuse me, could I get a Fig Bourbon Sour?", "One Fig Lemon Sour, please.", "Can we start a tab?"],
    levels: { beginner: "Do you like hosting?", intermediate: "Describe a gathering you really enjoyed.", advanced: "How do hospitality customs differ across cultures?" },
    reflection: "What useful phrase did you use today?",
  },
  {
    id: "fall-8", n: 8, theme: "Gratitude & Reflection",
    setting: "Friends reflecting together at the end of the season.",
    objective: "Share something you appreciate, respond warmly and propose a final toast.",
    dialogue: [
      { speaker: "Skyler", line: "This season has gone by quickly." },
      { speaker: "Parker", line: "It has. What are you most grateful for?" },
      { speaker: "Skyler", line: "The time I spent with family. How about you?" },
      { speaker: "Parker", line: "The people who encouraged me when work got difficult." },
    ],
    cocktail: { name: "Pomegranate Royale", ingredients: "Pomegranate · Gin · Lemon · Sparkling wine", note: "Bright, elegant and celebratory — a final toast to connection and growth." },
    mocktail: { name: "Pomegranate Rosemary Fizz", ingredients: "Pomegranate · Rosemary · Lemon · Soda", note: "Festive colour, herbal aroma and lively bubbles without the alcohol." },
    keyPhrases: ["This season went by quickly.", "What are you grateful for?", "I'm grateful for...", "How about you?", "I really appreciated...", "Here's to what comes next."],
    pairQuestions: ["What are you grateful for right now?", "Who has supported or encouraged you recently?"],
    rolePlay: "Share something you appreciate, respond warmly and propose a final toast.",
    mixAndSpeak: ["I'll have the Pomegranate Royale.", "A Rosemary Fizz for me, please.", "Here's to what comes next!"],
    levels: { beginner: "What made you happy this fall?", intermediate: "Describe a person whose support mattered to you.", advanced: "How does practising gratitude affect relationships and resilience?" },
    reflection: "What useful phrase did you use today?",
  },
];

// ─────────────────────────────────────────────────────────────────────────
// WINTER BAR
// ─────────────────────────────────────────────────────────────────────────
const WINTER = [
  {
    id: "winter-1", n: 1, theme: "Winter Arrivals & Staying Warm",
    setting: "Two friends arriving at a warm café on a cold evening.",
    objective: "Meet a friend after coming in from the cold and compare winter routines.",
    dialogue: [
      { speaker: "Alex", line: "It's freezing out there tonight." },
      { speaker: "Sam",  line: "I know. I could barely feel my hands by the time I got here." },
      { speaker: "Alex", line: "At least it's warm inside. How are you coping with the cold?" },
      { speaker: "Sam",  line: "Layers, hot drinks and staying home whenever I can." },
    ],
    cocktail: { name: "Cranberry Spice Spritz", ingredients: "Gin · Cranberry · Cinnamon · Sparkling wine", note: "Bright berry, warming spice and bubbles — a lively welcome to winter." },
    mocktail: { name: "Cranberry Cinnamon Fizz", ingredients: "Cranberry · Cinnamon · Orange · Soda water", note: "Festive, tart and alcohol-free, with a gentle winter warmth." },
    keyPhrases: ["It's freezing out there.", "I could barely feel my hands.", "At least it's warm inside.", "How are you coping with the cold?", "I've been bundling up.", "I stay in whenever I can."],
    pairQuestions: ["How do you feel about cold weather?", "What helps you stay warm and comfortable?"],
    rolePlay: "Meet a friend after coming in from the cold and compare winter routines.",
    mixAndSpeak: ["I'll start with the Cranberry Spice Spritz.", "Could I have the Cinnamon Fizz?", "What would you recommend for a cold evening?"],
    levels: { beginner: "Do you like winter?", intermediate: "Describe your ideal winter evening.", advanced: "How does winter weather affect people's routines and wellbeing?" },
    reflection: "What useful phrase did you use today?",
  },
  {
    id: "winter-2", n: 2, theme: "Indoor Hobbies & Slow Evenings",
    setting: "Friends relaxing in a quiet lounge after work.",
    objective: "Discuss indoor hobbies and recommend something your partner could try.",
    dialogue: [
      { speaker: "Jordan", line: "What do you do when it's too cold to go out?" },
      { speaker: "Taylor", line: "I've been watching old films and learning to bake bread." },
      { speaker: "Jordan", line: "That sounds cozy. I've been meaning to read more." },
      { speaker: "Taylor", line: "Winter is perfect for that. You should start a new book tonight." },
    ],
    cocktail: { name: "Hot Buttered Rum", ingredients: "Dark rum · Butter · Brown sugar · Winter spice", note: "Rich, warming and slow-sipping — made for a relaxed night indoors." },
    mocktail: { name: "Spiced Apple Warmer", ingredients: "Apple · Cinnamon · Clove · Orange peel", note: "Comforting fruit and spice in a cozy alcohol-free winter drink." },
    keyPhrases: ["What do you do when...?", "I've been...", "That sounds cozy.", "I've been meaning to...", "Winter is perfect for that.", "You should start..."],
    pairQuestions: ["How do you spend a quiet winter evening?", "What indoor skill would you like to learn?"],
    rolePlay: "Discuss indoor hobbies and recommend something your partner could try.",
    mixAndSpeak: ["I'm looking for something warming.", "Is the apple drink very spicy?", "I'll take the Spiced Apple Warmer."],
    levels: { beginner: "What is your favourite indoor activity?", intermediate: "How do you avoid feeling bored in winter?", advanced: "Why can slowing down be valuable in a culture that prizes productivity?" },
    reflection: "What useful phrase did you use today?",
  },
  {
    id: "winter-3", n: 3, theme: "Winter Travel & Weather Plans",
    setting: "Two friends discussing a possible winter getaway.",
    objective: "Compare two destinations, check the weather and choose the safer plan.",
    dialogue: [
      { speaker: "Casey",  line: "Are you planning to go anywhere this winter?" },
      { speaker: "Morgan", line: "I'm thinking about a weekend in the mountains." },
      { speaker: "Casey",  line: "That sounds great, but have you checked the forecast?" },
      { speaker: "Morgan", line: "Not yet. I'll keep an eye on it before I book anything." },
    ],
    cocktail: { name: "Alpine Gin Collins", ingredients: "Gin · Lemon · Rosemary · Soda water", note: "Crisp, herbal and refreshing — inspired by clear mountain air." },
    mocktail: { name: "Snowy Citrus Sparkler", ingredients: "White grapefruit · Lemon · Rosemary · Soda", note: "Clean citrus and lively bubbles for a bright alcohol-free escape." },
    keyPhrases: ["Are you planning to go anywhere?", "I'm thinking about...", "Have you checked the forecast?", "Not yet.", "I'll keep an eye on it.", "Before I book anything..."],
    pairQuestions: ["Where would you go for a winter getaway?", "Do you enjoy snow activities or warm escapes?"],
    rolePlay: "Compare two destinations, check possible weather and choose the safer plan.",
    mixAndSpeak: ["Something crisp and herbal, please.", "Could you make that alcohol-free?", "I'll have the Snowy Citrus Sparkler."],
    levels: { beginner: "Where do you want to travel?", intermediate: "Describe a memorable winter trip.", advanced: "How should travellers prepare for increasingly unpredictable weather?" },
    reflection: "What useful phrase did you use today?",
  },
  {
    id: "winter-4", n: 4, theme: "Comfort Food & Hot Drinks",
    setting: "Looking at a winter menu in a warm restaurant.",
    objective: "Discuss a winter menu, ask about portions and choose a comforting meal.",
    dialogue: [
      { speaker: "Riley", line: "I need something warm after being outside all day." },
      { speaker: "Jamie", line: "Same. The stew sounds exactly what I need." },
      { speaker: "Riley", line: "I'm tempted by the baked pasta, but it looks filling." },
      { speaker: "Jamie", line: "We could share it and order some soup as well." },
    ],
    cocktail: { name: "Irish Coffee", ingredients: "Irish whiskey · Coffee · Brown sugar · Cream", note: "Warm, rich and classic — a natural finish to a comforting winter meal." },
    mocktail: { name: "Vanilla Maple Latte", ingredients: "Espresso · Milk · Vanilla · Maple", note: "Smooth, gently sweet and cozy without the alcohol." },
    keyPhrases: ["I need something warm.", "That's exactly what I need.", "I'm tempted by...", "It looks filling.", "We could share it.", "What comes with it?"],
    pairQuestions: ["What food do you crave in cold weather?", "Which hot drink helps you feel comfortable?"],
    rolePlay: "Discuss a winter menu, ask about portions and choose a comforting meal.",
    mixAndSpeak: ["Could I get that with oat milk?", "Is the latte very sweet?", "What would you pair with the stew?"],
    levels: { beginner: "What is your favourite hot drink?", intermediate: "Describe a meal that makes you feel at home.", advanced: "Why are comfort foods strongly connected to culture and memory?" },
    reflection: "What useful phrase did you use today?",
  },
  {
    id: "winter-5", n: 5, theme: "Seasonal Traditions & Celebrations",
    setting: "Friends comparing winter traditions over drinks.",
    objective: "Share a seasonal tradition and ask how your partner celebrates differently.",
    dialogue: [
      { speaker: "Drew",   line: "What did winter celebrations look like in your family?" },
      { speaker: "Harper", line: "We always had a big meal and stayed up late talking." },
      { speaker: "Drew",   line: "That sounds lovely. Do you still do that now?" },
      { speaker: "Harper", line: "We do, although the traditions have changed a little." },
    ],
    cocktail: { name: "Mulled Red Wine", ingredients: "Red wine · Orange · Cinnamon · Clove", note: "Warm, fragrant and made for sharing at a festive winter gathering." },
    mocktail: { name: "Mulled Berry Punch", ingredients: "Berry juice · Orange · Cinnamon · Clove", note: "Rich fruit and warming spice in a celebratory alcohol-free punch." },
    keyPhrases: ["What did ... look like in your family?", "We always used to...", "That sounds lovely.", "Do you still do that now?", "The tradition has changed.", "We make time for..."],
    pairQuestions: ["Which winter tradition matters to you?", "Have your family celebrations changed over time?"],
    rolePlay: "Share a seasonal tradition and ask how your partner celebrates differently.",
    mixAndSpeak: ["We'll share some Mulled Red Wine.", "Could I get the berry punch?", "Make it two, please."],
    levels: { beginner: "What do you celebrate in winter?", intermediate: "Describe a meaningful family tradition.", advanced: "How do traditions evolve when families live across different cultures?" },
    reflection: "What useful phrase did you use today?",
  },
  {
    id: "winter-6", n: 6, theme: "New Year Goals & Fresh Starts",
    setting: "A café conversation during the first week of the year.",
    objective: "Share one goal, make it specific and agree on the first small action.",
    dialogue: [
      { speaker: "Quinn", line: "Have you set any goals for the new year?" },
      { speaker: "Avery", line: "A few, but I'm trying to keep them realistic." },
      { speaker: "Quinn", line: "That's probably wise. What's your main focus?" },
      { speaker: "Avery", line: "Building better habits instead of chasing one big result." },
    ],
    cocktail: { name: "Winter French 75", ingredients: "Gin · Lemon · Cranberry · Sparkling wine", note: "Bright, elegant and celebratory — a sparkling drink for a fresh beginning." },
    mocktail: { name: "Elderflower Lemon Sparkler", ingredients: "Elderflower · Lemon · Cranberry · Soda", note: "Floral, citrusy and festive, with no alcohol required for the toast." },
    keyPhrases: ["Have you set any goals?", "I'm keeping them realistic.", "That's probably wise.", "What's your main focus?", "I'm working on building...", "One step at a time."],
    pairQuestions: ["What would you like to improve this year?", "How do you make a goal feel realistic?"],
    rolePlay: "Share one goal, make it specific and agree on the first small action.",
    mixAndSpeak: ["I'll have the Winter French 75.", "An Elderflower Sparkler for me.", "Here's to a fresh start!"],
    levels: { beginner: "What is one goal you have?", intermediate: "Describe a habit you successfully changed.", advanced: "Are New Year resolutions helpful motivation or unnecessary pressure?" },
    reflection: "What useful phrase did you use today?",
  },
  {
    id: "winter-7", n: 7, theme: "Invitations & Winter Hosting",
    setting: "Friends arranging a relaxed dinner at home.",
    objective: "Invite your partner to dinner and discuss the time, directions and what to bring.",
    dialogue: [
      { speaker: "Blake",   line: "Would you like to come over for dinner on Saturday?" },
      { speaker: "Charlie", line: "I'd love to. What time should I come?" },
      { speaker: "Blake",   line: "Around seven. And don't worry about bringing anything." },
      { speaker: "Charlie", line: "Are you sure? I could bring dessert." },
    ],
    cocktail: { name: "Rosemary Negroni", ingredients: "Gin · Vermouth · Bitter aperitif · Rosemary", note: "Bold, aromatic and sophisticated — a confident drink for a winter gathering." },
    mocktail: { name: "Blood Orange Rosemary Soda", ingredients: "Blood orange · Rosemary · Lemon · Soda", note: "Vivid citrus and fragrant herbs in an elegant alcohol-free serve." },
    keyPhrases: ["Would you like to come over?", "I'd love to.", "What time should I come?", "Don't worry about bringing anything.", "Are you sure?", "I could bring..."],
    pairQuestions: ["Do you enjoy hosting people at home?", "What makes guests feel welcome?"],
    rolePlay: "Invite your partner to dinner and discuss the time, directions and what to bring.",
    mixAndSpeak: ["Could I get a Rosemary Negroni?", "One Blood Orange Soda, please.", "Can we start a tab?"],
    levels: { beginner: "Do you like having guests?", intermediate: "Describe a warm and welcoming host.", advanced: "How do hosting expectations differ between cultures?" },
    reflection: "What useful phrase did you use today?",
  },
  {
    id: "winter-8", n: 8, theme: "Winter Memories & Connection",
    setting: "Friends reflecting beside a window on a snowy evening.",
    objective: "Share a winter memory, respond with interest and propose a final toast.",
    dialogue: [
      { speaker: "Skyler", line: "The snow tonight reminds me of winters when I was a child." },
      { speaker: "Parker", line: "What do you remember most?" },
      { speaker: "Skyler", line: "Coming home, getting warm and talking with my family." },
      { speaker: "Parker", line: "It's funny how small moments become important memories." },
    ],
    cocktail: { name: "Pear Brandy Sour", ingredients: "Pear brandy · Lemon · Honey · Bitters", note: "Smooth fruit and bright citrus — a thoughtful final toast to the season." },
    mocktail: { name: "Pear Ginger Fizz", ingredients: "Pear · Ginger · Lemon · Soda water", note: "Fresh, gently spicy and sparkling, with a clean winter finish." },
    keyPhrases: ["This reminds me of...", "What do you remember most?", "When I was a child...", "It's funny how...", "That memory has stayed with me.", "Here's to staying connected."],
    pairQuestions: ["What winter memory makes you smile?", "Who would you like to spend more time with?"],
    rolePlay: "Share a winter memory, respond with interest and propose a final toast.",
    mixAndSpeak: ["I'll have the Pear Brandy Sour.", "A Pear Ginger Fizz for me.", "Here's to staying connected!"],
    levels: { beginner: "What do you remember about winter?", intermediate: "Describe a small moment that became meaningful.", advanced: "Why are shared memories so important to strong relationships?" },
    reflection: "What useful phrase did you use today?",
  },
];

export const LESSONS_BY_SEASON = {
  spring: SPRING,
  summer: SUMMER,
  fall:   FALL,
  winter: WINTER,
};

// Flat lookup by lesson id (e.g. "winter-3").
export const LESSON_MAP = Object.fromEntries(
  Object.values(LESSONS_BY_SEASON).flat().map((l) => [l.id, l])
);

export const TOTAL_LESSONS = Object.values(LESSONS_BY_SEASON).reduce((n, arr) => n + arr.length, 0);

export function getLesson(seasonId, n) {
  return (LESSONS_BY_SEASON[seasonId] || []).find((l) => l.n === n) || null;
}

// Estimated minutes per lesson (Hear + See + Do), shown on cards.
export const LESSON_DURATION_MIN = "15–20 min";

// Per-lesson scene image (used on lesson cards + the HEAR scene). Files live in
// public/ssl/lessons/ named ssl-lesson-{season}-{n}.jpg (e.g. ssl-lesson-winter-3.jpg).
export const lessonThumb = (id) => `/ssl/lessons/ssl-lesson-${id}.jpg`;
